/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ExercisesApi
import org.openapitools.client.models.LogExerciseRequest
import org.openapitools.client.models.LogExerciseResponse
import org.openapitools.client.models.PaginatedExerciseHistoryResponse

class ExercisesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExercisesApi
        //val apiInstance = ExercisesApi()

        // to test exercisesGet
        should("test exercisesGet") {
            // uncomment below to test exercisesGet
            //val page : kotlin.Int = 56 // kotlin.Int | Page number for pagination
            //val pageSize : kotlin.Int = 56 // kotlin.Int | Number of items per page
            //val result : PaginatedExerciseHistoryResponse = apiInstance.exercisesGet(page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test exercisesPost
        should("test exercisesPost") {
            // uncomment below to test exercisesPost
            //val logExerciseRequest : LogExerciseRequest =  // LogExerciseRequest | 
            //val result : LogExerciseResponse = apiInstance.exercisesPost(logExerciseRequest)
            //result shouldBe ("TODO")
        }

    }
}
