/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.SyncApi
import org.openapitools.client.models.SyncRequest
import org.openapitools.client.models.SyncResponse

class SyncApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SyncApi
        //val apiInstance = SyncApi()

        // to test syncPost
        should("test syncPost") {
            // uncomment below to test syncPost
            //val syncRequest : SyncRequest =  // SyncRequest | 
            //val result : SyncResponse = apiInstance.syncPost(syncRequest)
            //result shouldBe ("TODO")
        }

    }
}
