/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UsersApi
import org.openapitools.client.models.UpdateUserRequest
import org.openapitools.client.models.User

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test usersMePatch
        should("test usersMePatch") {
            // uncomment below to test usersMePatch
            //val updateUserRequest : UpdateUserRequest =  // UpdateUserRequest | 
            //val result : User = apiInstance.usersMePatch(updateUserRequest)
            //result shouldBe ("TODO")
        }

    }
}
