/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.WorkoutsApi
import org.openapitools.client.models.PaginatedWorkoutsResponse

class WorkoutsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkoutsApi
        //val apiInstance = WorkoutsApi()

        // to test handleGetWorkouts
        should("test handleGetWorkouts") {
            // uncomment below to test handleGetWorkouts
            //val page : kotlin.Int = 56 // kotlin.Int | Page number for pagination
            //val pageSize : kotlin.Int = 56 // kotlin.Int | Number of items per page
            //val result : PaginatedWorkoutsResponse = apiInstance.handleGetWorkouts(page, pageSize)
            //result shouldBe ("TODO")
        }

    }
}
