disabled_rules:
  - trailing_whitespace
  - line_length
  
included:
  - ios/ptchampion
  - ios/PTDesignSystem
  
excluded:
  - ios/ptchampion/Resources
  
analyzer_rules:
  - unused_declaration
  - unused_import
  
identifier_name:
  min_length: 2
  excluded:
    - id
    - i
    - j
    - x
    - y
    
type_body_length:
  warning: 400
  error: 600
  
function_body_length:
  warning: 100
  error: 200
  
cyclomatic_complexity:
  warning: 15
  error: 30
  
nesting:
  type_level: 3
  
trailing_comma:
  mandatory_comma: true 