/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandleGetLocalLeaderboard200ResponseInner

class HandleGetLocalLeaderboard200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandleGetLocalLeaderboard200ResponseInner
        //val modelInstance = HandleGetLocalLeaderboard200ResponseInner()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `exerciseId`
        should("test exerciseId") {
            // uncomment below to test the property
            //modelInstance.exerciseId shouldBe ("TODO")
        }

        // to test the property `score`
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

    }
}
