/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandleUpdateUserLocationRequest

class HandleUpdateUserLocationRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandleUpdateUserLocationRequest
        //val modelInstance = HandleUpdateUserLocationRequest()

        // to test the property `latitude` - Latitude (WGS 84)
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude` - Longitude (WGS 84)
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

    }
}
