/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.InsertUserExercise

class InsertUserExerciseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InsertUserExercise
        //val modelInstance = InsertUserExercise()

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `exerciseId`
        should("test exerciseId") {
            // uncomment below to test the property
            //modelInstance.exerciseId shouldBe ("TODO")
        }

        // to test the property `repetitions`
        should("test repetitions") {
            // uncomment below to test the property
            //modelInstance.repetitions shouldBe ("TODO")
        }

        // to test the property `formScore`
        should("test formScore") {
            // uncomment below to test the property
            //modelInstance.formScore shouldBe ("TODO")
        }

        // to test the property `timeInSeconds`
        should("test timeInSeconds") {
            // uncomment below to test the property
            //modelInstance.timeInSeconds shouldBe ("TODO")
        }

        // to test the property `grade`
        should("test grade") {
            // uncomment below to test the property
            //modelInstance.grade shouldBe ("TODO")
        }

        // to test the property `completed`
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `syncStatus`
        should("test syncStatus") {
            // uncomment below to test the property
            //modelInstance.syncStatus shouldBe ("TODO")
        }

    }
}
