/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PaginatedWorkoutsResponse
import org.openapitools.client.models.WorkoutResponse

class PaginatedWorkoutsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedWorkoutsResponse
        //val modelInstance = PaginatedWorkoutsResponse()

        // to test the property `workouts`
        should("test workouts") {
            // uncomment below to test the property
            //modelInstance.workouts shouldBe ("TODO")
        }

        // to test the property `totalCount`
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

        // to test the property `page`
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `pageSize`
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

        // to test the property `totalPages`
        should("test totalPages") {
            // uncomment below to test the property
            //modelInstance.totalPages shouldBe ("TODO")
        }

    }
}
