/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PaginatedExerciseHistoryResponse
import org.openapitools.client.models.PaginatedExerciseHistoryResponseItemsInner

class PaginatedExerciseHistoryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedExerciseHistoryResponse
        //val modelInstance = PaginatedExerciseHistoryResponse()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `totalCount`
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

        // to test the property `page`
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `pageSize`
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

    }
}
