/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SyncRequestData
import org.openapitools.client.models.SyncRequestDataProfile
import org.openapitools.client.models.SyncRequestDataUserExercisesInner

class SyncRequestDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SyncRequestData
        //val modelInstance = SyncRequestData()

        // to test the property `userExercises`
        should("test userExercises") {
            // uncomment below to test the property
            //modelInstance.userExercises shouldBe ("TODO")
        }

        // to test the property `profile`
        should("test profile") {
            // uncomment below to test the property
            //modelInstance.profile shouldBe ("TODO")
        }

    }
}
