/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Data required to register a new user
 *
 * @param username 
 * @param password 
 * @param displayName 
 * @param profilePictureUrl 
 * @param location 
 * @param latitude 
 * @param longitude 
 */


data class InsertUser (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "profilePictureUrl")
    val profilePictureUrl: kotlin.String? = null,

    @Json(name = "location")
    val location: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: kotlin.String? = null,

    @Json(name = "longitude")
    val longitude: kotlin.String? = null

) {


}

