/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param displayName 
 * @param bestGrade 
 */


data class LeaderboardResponseInner (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "display_name")
    val displayName: kotlin.String,

    @Json(name = "best_grade")
    val bestGrade: kotlin.Int

) {


}

