/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Logged exercise data with calculated grade
 *
 * @param id 
 * @param userId 
 * @param exerciseId 
 * @param exerciseName 
 * @param exerciseType 
 * @param grade 
 * @param createdAt 
 * @param reps 
 * @param timeInSeconds 
 * @param distance 
 * @param notes 
 */


data class LogExerciseResponse (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "user_id")
    val userId: kotlin.Int,

    @Json(name = "exercise_id")
    val exerciseId: kotlin.Int,

    @Json(name = "exercise_name")
    val exerciseName: kotlin.String,

    @Json(name = "exercise_type")
    val exerciseType: kotlin.String,

    @Json(name = "grade")
    val grade: kotlin.Int,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "reps")
    val reps: kotlin.Int? = null,

    @Json(name = "time_in_seconds")
    val timeInSeconds: kotlin.Int? = null,

    @Json(name = "distance")
    val distance: kotlin.Int? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null

) {


}

