/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Exercise data to log
 *
 * @param exerciseId 
 * @param reps 
 * @param duration 
 * @param distance 
 * @param notes 
 * @param formScore Optional score (0-100) from client-side form analysis
 * @param completed Whether the exercise was fully completed
 * @param deviceId Optional identifier of the device used for logging
 */


data class LogExerciseRequest (

    @Json(name = "exercise_id")
    val exerciseId: kotlin.Int,

    @Json(name = "reps")
    val reps: kotlin.Int? = null,

    @Json(name = "duration")
    val duration: kotlin.Int? = null,

    @Json(name = "distance")
    val distance: kotlin.Int? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Optional score (0-100) from client-side form analysis */
    @Json(name = "form_score")
    val formScore: kotlin.Int? = null,

    /* Whether the exercise was fully completed */
    @Json(name = "completed")
    val completed: kotlin.Boolean? = null,

    /* Optional identifier of the device used for logging */
    @Json(name = "device_id")
    val deviceId: kotlin.String? = null

) {


}

