/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.WorkoutResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Paginated list of workout sessions
 *
 * @param workouts 
 * @param totalCount 
 * @param page 
 * @param pageSize 
 * @param totalPages 
 */


data class PaginatedWorkoutsResponse (

    @Json(name = "workouts")
    val workouts: kotlin.collections.List<WorkoutResponse>,

    @Json(name = "totalCount")
    val totalCount: kotlin.Long,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "pageSize")
    val pageSize: kotlin.Int,

    @Json(name = "totalPages")
    val totalPages: kotlin.Int

) {


}

