/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaginatedExerciseHistoryResponseItemsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Paginated exercise history for user
 *
 * @param items 
 * @param totalCount 
 * @param page 
 * @param pageSize 
 */


data class PaginatedExerciseHistoryResponse (

    @Json(name = "items")
    val items: kotlin.collections.List<PaginatedExerciseHistoryResponseItemsInner>,

    @Json(name = "total_count")
    val totalCount: kotlin.Int,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "page_size")
    val pageSize: kotlin.Int

) {


}

