/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SyncRequestDataProfile
import org.openapitools.client.models.SyncRequestDataUserExercisesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userExercises 
 * @param profile 
 */


data class SyncRequestData (

    @Json(name = "userExercises")
    val userExercises: kotlin.collections.List<SyncRequestDataUserExercisesInner>? = null,

    @Json(name = "profile")
    val profile: SyncRequestDataProfile? = null

) {


}

