/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param userId 
 * @param exerciseId 
 * @param repetitions 
 * @param formScore 
 * @param timeInSeconds 
 * @param grade 
 * @param completed 
 * @param metadata 
 * @param deviceId 
 * @param syncStatus 
 */


data class SyncRequestDataUserExercisesInner (

    @Json(name = "userId")
    val userId: kotlin.Int,

    @Json(name = "exerciseId")
    val exerciseId: kotlin.Int,

    @Json(name = "repetitions")
    val repetitions: kotlin.Int? = null,

    @Json(name = "formScore")
    val formScore: kotlin.Int? = null,

    @Json(name = "timeInSeconds")
    val timeInSeconds: kotlin.Int? = null,

    @Json(name = "grade")
    val grade: kotlin.Int? = null,

    @Json(name = "completed")
    val completed: kotlin.Boolean? = null,

    @Json(name = "metadata")
    val metadata: kotlin.String? = null,

    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    @Json(name = "syncStatus")
    val syncStatus: kotlin.String? = null

) {


}

