/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Data for updating a user profile
 *
 * @param displayName 
 * @param profilePictureUrl 
 * @param location 
 */


data class UpdateProfile (

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "profilePictureUrl")
    val profilePictureUrl: kotlin.String? = null,

    @Json(name = "location")
    val location: kotlin.String? = null

) {


}

