/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * User profile information
 *
 * @param id 
 * @param username 
 * @param displayName 
 * @param profilePictureUrl 
 * @param location 
 * @param latitude 
 * @param longitude 
 * @param lastSyncedAt 
 * @param createdAt 
 * @param updatedAt 
 */


data class User (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "displayName")
    val displayName: kotlin.String?,

    @Json(name = "profilePictureUrl")
    val profilePictureUrl: java.net.URI?,

    @Json(name = "location")
    val location: kotlin.String?,

    @Json(name = "latitude")
    val latitude: kotlin.String?,

    @Json(name = "longitude")
    val longitude: kotlin.String?,

    @Json(name = "lastSyncedAt")
    val lastSyncedAt: kotlin.String?,

    @Json(name = "createdAt")
    val createdAt: kotlin.String?,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String?

) {


}

