blank_issues_enabled: false
contact_links:
  - name: PT Champion Support
    url: https://github.com/username/ptchampion/discussions
    about: Please ask and answer questions through GitHub Discussions. 