// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: leaderboard.sql

package db

import (
	"context"
	"database/sql"
)

const getLeaderboardByExerciseType = `-- name: GetLeaderboardByExerciseType :many
SELECT 
    u.username,
    u.display_name,
    e.type as exercise_type,
    MAX(ue.grade) as best_grade -- Get the best grade for this exercise type per user
FROM user_exercises ue
JOIN users u ON ue.user_id = u.id
JOIN exercises e ON ue.exercise_id = e.id
WHERE e.type = $1
AND ue.grade IS NOT NULL
GROUP BY u.id, e.type -- Group by user to find their best score for this exercise
ORDER BY best_grade DESC
LIMIT $2
`

type GetLeaderboardByExerciseTypeParams struct {
	Type  string `json:"type"`
	Limit int32  `json:"limit"`
}

type GetLeaderboardByExerciseTypeRow struct {
	Username     string         `json:"username"`
	DisplayName  sql.NullString `json:"display_name"`
	ExerciseType string         `json:"exercise_type"`
	BestGrade    interface{}    `json:"best_grade"`
}

func (q *Queries) GetLeaderboardByExerciseType(ctx context.Context, arg GetLeaderboardByExerciseTypeParams) ([]GetLeaderboardByExerciseTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboardByExerciseType, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardByExerciseTypeRow{}
	for rows.Next() {
		var i GetLeaderboardByExerciseTypeRow
		if err := rows.Scan(
			&i.Username,
			&i.DisplayName,
			&i.ExerciseType,
			&i.BestGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
