// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
}

type User struct {
	ID                int32          `json:"id"`
	Username          string         `json:"username"`
	Password          string         `json:"password"`
	DisplayName       sql.NullString `json:"display_name"`
	ProfilePictureUrl sql.NullString `json:"profile_picture_url"`
	Location          sql.NullString `json:"location"`
	Latitude          sql.NullString `json:"latitude"`
	Longitude         sql.NullString `json:"longitude"`
	LastLocation      sql.NullString `json:"last_location"`
	LastSyncedAt      sql.NullTime   `json:"last_synced_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type UserExercise struct {
	ID            int32          `json:"id"`
	UserID        int32          `json:"user_id"`
	ExerciseID    int32          `json:"exercise_id"`
	Repetitions   sql.NullInt32  `json:"repetitions"`
	TimeInSeconds sql.NullInt32  `json:"time_in_seconds"`
	Distance      sql.NullInt32  `json:"distance"`
	FormScore     sql.NullInt32  `json:"form_score"`
	Grade         sql.NullInt32  `json:"grade"`
	Completed     sql.NullBool   `json:"completed"`
	Metadata      sql.NullString `json:"metadata"`
	Notes         sql.NullString `json:"notes"`
	DeviceID      sql.NullString `json:"device_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Workout struct {
	ID              int32         `json:"id"`
	UserID          int32         `json:"user_id"`
	ExerciseID      int32         `json:"exercise_id"`
	ExerciseType    string        `json:"exercise_type"`
	Repetitions     sql.NullInt32 `json:"repetitions"`
	DurationSeconds sql.NullInt32 `json:"duration_seconds"`
	FormScore       sql.NullInt32 `json:"form_score"`
	Grade           int32         `json:"grade"`
	CompletedAt     time.Time     `json:"completed_at"`
	CreatedAt       time.Time     `json:"created_at"`
}
