// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	GetExercise(ctx context.Context, id int32) (Exercise, error)
	GetExercisesByType(ctx context.Context, type_ string) ([]Exercise, error)
	GetLeaderboard(ctx context.Context, type_ string) ([]GetLeaderboardRow, error)
	GetLeaderboardByExerciseType(ctx context.Context, arg GetLeaderboardByExerciseTypeParams) ([]GetLeaderboardByExerciseTypeRow, error)
	// Limit the number of results (e.g., top 10, 20)
	GetLocalLeaderboard(ctx context.Context, arg GetLocalLeaderboardParams) ([]GetLocalLeaderboardRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserExercises(ctx context.Context, arg GetUserExercisesParams) ([]GetUserExercisesRow, error)
	GetUserExercisesByType(ctx context.Context, arg GetUserExercisesByTypeParams) ([]GetUserExercisesByTypeRow, error)
	GetUserExercisesCount(ctx context.Context, userID int32) (int64, error)
	GetUserWorkouts(ctx context.Context, arg GetUserWorkoutsParams) ([]GetUserWorkoutsRow, error)
	GetUserWorkoutsCount(ctx context.Context, userID int32) (int64, error)
	ListExercises(ctx context.Context) ([]Exercise, error)
	LogUserExercise(ctx context.Context, arg LogUserExerciseParams) (UserExercise, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLocation(ctx context.Context, arg UpdateUserLocationParams) error
}

var _ Querier = (*Queries)(nil)
