/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param latitude Latitude (WGS 84)
 * @param longitude Longitude (WGS 84)
 */
@JsonClass(generateAdapter = true)

data class HandleUpdateUserLocationRequest (

    /* Latitude (WGS 84) */
    @Json(name = "latitude")
    val latitude: kotlin.Double,

    /* Longitude (WGS 84) */
    @Json(name = "longitude")
    val longitude: kotlin.Double

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

