/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param username 
 * @param displayName 
 * @param bestGrade 
 */
@JsonClass(generateAdapter = true)

data class LeaderboardResponseInner (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "display_name")
    val displayName: kotlin.String,

    @Json(name = "best_grade")
    val bestGrade: kotlin.Int

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

