/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.User
import org.openapitools.client.models.UserExercise

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param userExercises 
 * @param profile 
 */
@JsonClass(generateAdapter = true)

data class SyncResponseData (

    @Json(name = "userExercises")
    val userExercises: kotlin.collections.List<UserExercise>? = null,

    @Json(name = "profile")
    val profile: User? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

