/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SyncRequestData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * Request payload for synchronizing data
 *
 * @param userId 
 * @param deviceId 
 * @param lastSyncTimestamp 
 * @param `data` 
 */
@JsonClass(generateAdapter = true)

data class SyncRequest (

    @Json(name = "userId")
    val userId: kotlin.Int,

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "lastSyncTimestamp")
    val lastSyncTimestamp: java.time.OffsetDateTime,

    @Json(name = "data")
    val `data`: SyncRequestData? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

