/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param displayName 
 * @param profilePictureUrl 
 * @param location 
 */
@JsonClass(generateAdapter = true)

data class SyncRequestDataProfile (

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "profilePictureUrl")
    val profilePictureUrl: kotlin.String? = null,

    @Json(name = "location")
    val location: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

