/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SyncResponseData
import org.openapitools.client.models.UserExercise

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * Response payload after data synchronization
 *
 * @param success 
 * @param timestamp 
 * @param `data` 
 * @param conflicts 
 */
@JsonClass(generateAdapter = true)

data class SyncResponse (

    @Json(name = "success")
    val success: kotlin.Boolean,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    @Json(name = "data")
    val `data`: SyncResponseData? = null,

    @Json(name = "conflicts")
    val conflicts: kotlin.collections.List<UserExercise>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

