/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * Details of a completed or tracked exercise
 *
 * @param id 
 * @param userId 
 * @param exerciseId 
 * @param repetitions 
 * @param formScore 
 * @param timeInSeconds 
 * @param grade 
 * @param completed 
 * @param metadata 
 * @param deviceId 
 * @param syncStatus 
 * @param createdAt 
 * @param updatedAt 
 */
@JsonClass(generateAdapter = true)

data class UserExercise (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "userId")
    val userId: kotlin.Int,

    @Json(name = "exerciseId")
    val exerciseId: kotlin.Int,

    @Json(name = "repetitions")
    val repetitions: kotlin.Int?,

    @Json(name = "formScore")
    val formScore: kotlin.Int?,

    @Json(name = "timeInSeconds")
    val timeInSeconds: kotlin.Int?,

    @Json(name = "grade")
    val grade: kotlin.Int?,

    @Json(name = "completed")
    val completed: kotlin.Boolean,

    @Json(name = "metadata")
    val metadata: kotlin.String?,

    @Json(name = "deviceId")
    val deviceId: kotlin.String?,

    @Json(name = "syncStatus")
    val syncStatus: UserExercise.SyncStatus?,

    @Json(name = "createdAt")
    val createdAt: kotlin.String?,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String?

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 
     *
     * Values: synced,pending,conflict
     */
    @JsonClass(generateAdapter = false)
    enum class SyncStatus(val value: kotlin.String) {
        @Json(name = "synced") synced("synced"),
        @Json(name = "pending") pending("pending"),
        @Json(name = "conflict") conflict("conflict");
    }

}

