/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * A single recorded workout session
 *
 * @param id 
 * @param userId 
 * @param exerciseId 
 * @param exerciseName 
 * @param grade 
 * @param createdAt 
 * @param completedAt 
 * @param repetitions 
 * @param durationSeconds 
 * @param formScore 
 */
@JsonClass(generateAdapter = true)

data class WorkoutResponse (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "userId")
    val userId: kotlin.Int,

    @Json(name = "exerciseId")
    val exerciseId: kotlin.Int,

    @Json(name = "exerciseName")
    val exerciseName: kotlin.String,

    @Json(name = "grade")
    val grade: kotlin.Int,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "completedAt")
    val completedAt: java.time.OffsetDateTime,

    @Json(name = "repetitions")
    val repetitions: kotlin.Int? = null,

    @Json(name = "durationSeconds")
    val durationSeconds: kotlin.Int? = null,

    @Json(name = "formScore")
    val formScore: kotlin.Int? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

