disabled_rules:
  - trailing_whitespace
  - function_body_length
  - line_length
  - nesting
  - type_body_length
  - file_length
  - large_tuple
  - force_unwrapping # Disabled for now but we should enforce this later

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - multiline_parameters
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - ptchampion
excluded:
  - ptchampion/Generated
  - Pods
  - fastlane
  - vendor
  - **/Frameworks/**

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
    - to
    - dx
    - dy
    - i
    - j
    - r
    - g
    - b
    - a
    - vm
    - vc
    - up

custom_rules:
  use_generated_colors:
    name: "Use Generated Colors"
    regex: "AppTheme\\.Colors\\."
    message: "Use AppTheme.GeneratedColors instead of AppTheme.Colors"
    severity: warning
  
  use_generated_typography:
    name: "Use Generated Typography"
    regex: "AppTheme\\.Typography\\."
    message: "Use AppTheme.GeneratedTypography instead of AppTheme.Typography"
    severity: warning
    
  direct_color_usage:
    name: "Direct Color Usage"
    regex: "\\.foregroundColor\\((\\.deepOpsGreen|\\.brassGold|\\.tacticalGray|\\.commandBlack|\\.cream)"
    message: "Use AppTheme.GeneratedColors instead of direct color references"
    severity: warning
    
  font_custom_direct:
    name: "Direct Font Custom Usage"
    regex: "\\.font\\(\\.custom\\("
    message: "Use AppTheme.GeneratedTypography instead of direct font creation"
    severity: warning
    
  app_constants_spacing:
    name: "AppConstants Spacing Usage"
    regex: "AppConstants\\.Spacing\\."
    message: "Use AppTheme.GeneratedSpacing instead of AppConstants.Spacing"
    severity: warning
    
  app_constants_radius:
    name: "AppConstants Radius Usage"
    regex: "AppConstants\\.Radius\\."
    message: "Use AppTheme.GeneratedRadius instead of AppConstants.Radius"
    severity: warning
    
  app_constants_fontsize:
    name: "AppConstants FontSize Usage"
    regex: "AppConstants\\.FontSize\\."
    message: "Use AppTheme.GeneratedTypography size parameter instead of AppConstants.FontSize"
    severity: warning 