# Podfile for PT Champion iOS app

platform :ios, '14.0'

target 'PTChampion' do
  use_frameworks!

  # MediaPipe pose detection
  pod 'MediaPipeTasksVision', '~> 0.10.0'
  
  # Other dependencies might go here
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # Enable arm64 architecture for simulator (for Apple Silicon)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
