/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.LogExerciseRequest

class LogExerciseRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogExerciseRequest
        //val modelInstance = LogExerciseRequest()

        // to test the property `exerciseId`
        should("test exerciseId") {
            // uncomment below to test the property
            //modelInstance.exerciseId shouldBe ("TODO")
        }

        // to test the property `reps`
        should("test reps") {
            // uncomment below to test the property
            //modelInstance.reps shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `distance`
        should("test distance") {
            // uncomment below to test the property
            //modelInstance.distance shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `formScore` - Optional score (0-100) from client-side form analysis
        should("test formScore") {
            // uncomment below to test the property
            //modelInstance.formScore shouldBe ("TODO")
        }

        // to test the property `completed` - Whether the exercise was fully completed
        should("test completed") {
            // uncomment below to test the property
            //modelInstance.completed shouldBe ("TODO")
        }

        // to test the property `deviceId` - Optional identifier of the device used for logging
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

    }
}
