/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.LogExerciseResponse

class LogExerciseResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogExerciseResponse
        //val modelInstance = LogExerciseResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `exerciseId`
        should("test exerciseId") {
            // uncomment below to test the property
            //modelInstance.exerciseId shouldBe ("TODO")
        }

        // to test the property `exerciseName`
        should("test exerciseName") {
            // uncomment below to test the property
            //modelInstance.exerciseName shouldBe ("TODO")
        }

        // to test the property `exerciseType`
        should("test exerciseType") {
            // uncomment below to test the property
            //modelInstance.exerciseType shouldBe ("TODO")
        }

        // to test the property `grade`
        should("test grade") {
            // uncomment below to test the property
            //modelInstance.grade shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `reps`
        should("test reps") {
            // uncomment below to test the property
            //modelInstance.reps shouldBe ("TODO")
        }

        // to test the property `timeInSeconds`
        should("test timeInSeconds") {
            // uncomment below to test the property
            //modelInstance.timeInSeconds shouldBe ("TODO")
        }

        // to test the property `distance`
        should("test distance") {
            // uncomment below to test the property
            //modelInstance.distance shouldBe ("TODO")
        }

        // to test the property `notes`
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

    }
}
