/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.WorkoutResponse

class WorkoutResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WorkoutResponse
        //val modelInstance = WorkoutResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `exerciseId`
        should("test exerciseId") {
            // uncomment below to test the property
            //modelInstance.exerciseId shouldBe ("TODO")
        }

        // to test the property `exerciseName`
        should("test exerciseName") {
            // uncomment below to test the property
            //modelInstance.exerciseName shouldBe ("TODO")
        }

        // to test the property `grade`
        should("test grade") {
            // uncomment below to test the property
            //modelInstance.grade shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `completedAt`
        should("test completedAt") {
            // uncomment below to test the property
            //modelInstance.completedAt shouldBe ("TODO")
        }

        // to test the property `repetitions`
        should("test repetitions") {
            // uncomment below to test the property
            //modelInstance.repetitions shouldBe ("TODO")
        }

        // to test the property `durationSeconds`
        should("test durationSeconds") {
            // uncomment below to test the property
            //modelInstance.durationSeconds shouldBe ("TODO")
        }

        // to test the property `formScore`
        should("test formScore") {
            // uncomment below to test the property
            //modelInstance.formScore shouldBe ("TODO")
        }

    }
}
