/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AuthApi
import org.openapitools.client.models.InsertUser
import org.openapitools.client.models.LoginRequest
import org.openapitools.client.models.LoginResponse
import org.openapitools.client.models.User

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test authLoginPost
        should("test authLoginPost") {
            // uncomment below to test authLoginPost
            //val loginRequest : LoginRequest =  // LoginRequest | 
            //val result : LoginResponse = apiInstance.authLoginPost(loginRequest)
            //result shouldBe ("TODO")
        }

        // to test authRegisterPost
        should("test authRegisterPost") {
            // uncomment below to test authRegisterPost
            //val insertUser : InsertUser =  // InsertUser | 
            //val result : User = apiInstance.authRegisterPost(insertUser)
            //result shouldBe ("TODO")
        }

    }
}
