/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ProfileApi
import org.openapitools.client.models.HandleUpdateUserLocationRequest

class ProfileApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProfileApi
        //val apiInstance = ProfileApi()

        // to test handleUpdateUserLocation
        should("test handleUpdateUserLocation") {
            // uncomment below to test handleUpdateUserLocation
            //val handleUpdateUserLocationRequest : HandleUpdateUserLocationRequest =  // HandleUpdateUserLocationRequest | 
            //apiInstance.handleUpdateUserLocation(handleUpdateUserLocationRequest)
        }

    }
}
