name: Generate & Publish API Docs

on:
  push:
    branches: [main]
    paths:
      - 'openapi.yaml'
      - '.github/workflows/api-docs.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for gh-pages publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ReDoc CLI
        run: npm install -g redoc-cli

      - name: Generate API documentation
        run: |
          mkdir -p docs/api
          redoc-cli bundle openapi.yaml --output docs/api/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          keep_files: true  # retain other docs if present in gh-pages 