name: Lighthouse CI

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/lighthouserc.json'
  pull_request:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/lighthouserc.json'

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build web assets
        working-directory: ./web
        run: |
          npm ci
          npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: '.github/lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true 